name: Build Enhanced DLL for Alkad 2588 WH
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Download Dependencies
      run: |
        mkdir dependencies
        curl -L -o dependencies/detours.zip https://github.com/microsoft/Detours/releases/download/v4.0.2/detours_binaries.zip
        curl -L -o dependencies/imgui.zip https://github.com/ocornut/imgui/releases/download/v1.91.6/imgui_binaries.zip
