name: Build Enhanced DLL for Alkad 2588 WH
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install NuGet
      run: |
        curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    - name: Install Detours and ImGui via NuGet
      run: |
        .\nuget.exe install Microsoft.Detours -Version 4.0.1 -OutputDirectory packages
        .\nuget.exe install imgui -Version 1.89.9 -OutputDirectory packages

    - name: Build DLL
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cl /Y- /O2 /MD /W4 /TP /EHsc /D "WIN32_LEAN_AND_MEAN" /D "NOMINMAX" /D "_HAS_PCH=0" /I "C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" /I "packages\Microsoft.Detours.4.0.1\lib.Native\include" /I "packages\imgui.1.89.9\build\native\include" enhanced_hack_v2.cpp /link /DLL /OUT:Dll1.dll /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" /LIBPATH:"packages\Microsoft.Detours.4.0.1\lib.Native\lib\x64" /LIBPATH:"packages\imgui.1.89.9\build\native\lib" d3d11.lib d3dcompiler.lib advapi32.lib winmm.lib detours.lib imgui.lib

    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: Dll1.dll
        path: Dll1.dll
